name: Homebrew Formula

on:
  release:
    types: [published]

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: nmsize
          homebrew-tap: smnandre/homebrew-nmsize
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_PAT }}
