name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release archive
        run: |
          mkdir -p release
          cp nmsize.sh release/
          cd release
          tar -czvf ../nmsize.tar.gz nmsize.sh

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: nmsize.tar.gz
