name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release archive
        run: |
          mkdir -p release
          cp nmsize.sh release/
          cd release
          tar -czvf ../nmsize.tar.gz nmsize.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: nmsize.tar.gz
