name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  sa:
    name: "Static Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bats tests
        uses: mig4/bats-action@v1
        with:
          bats-version: '1.8.2'
          test-files: 'test/*.bats'
